# Generated by Django 5.2.8 on 2025-11-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=200)),
                ('Book_ID', models.IntegerField()),
                ('Book_author', models.CharField(max_length=100)),
                ('Book_Issued_date', models.DateField()),
            ],
        ),
    ]
